// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshneosADQvOhqgy-MwW9nuKW_pWA7UR4',
    appId: '1:375854632042:web:0bbd1e1f6c1d47763d4e13',
    messagingSenderId: '375854632042',
    projectId: 'appuber-fb818',
    authDomain: 'appuber-fb818.firebaseapp.com',
    storageBucket: 'appuber-fb818.appspot.com',
    measurementId: 'G-YL6T0TDS76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZz8AONfuuurHN1KJoh4d9bo1NWJlslg',
    appId: '1:375854632042:android:b80cf99350211d033d4e13',
    messagingSenderId: '375854632042',
    projectId: 'appuber-fb818',
    storageBucket: 'appuber-fb818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RD08EPIVtIhh_WRWTVPjXY2RQN_AfJQ',
    appId: '1:375854632042:ios:38792e4412a4acb23d4e13',
    messagingSenderId: '375854632042',
    projectId: 'appuber-fb818',
    storageBucket: 'appuber-fb818.appspot.com',
    iosBundleId: 'com.example.indriverCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RD08EPIVtIhh_WRWTVPjXY2RQN_AfJQ',
    appId: '1:375854632042:ios:e4c75a1a896ebe153d4e13',
    messagingSenderId: '375854632042',
    projectId: 'appuber-fb818',
    storageBucket: 'appuber-fb818.appspot.com',
    iosBundleId: 'com.example.indriverCloneFlutter.RunnerTests',
  );
}
